### ISSUE TITLE
Update documentation to account for automatic context propagation

### ISSUE THREAD

**Issue by slashmo** [apple/swift-distributed-tracing#51] opened 2021-08-10 09:27 UTC
We should update the documentation to include a section about automatic context propagation, and remove any mention of the soon to be removed `LoggingContext`.

**Comment by ktoso** [comment] 2023-02-24 10:44
I'll mark this as Duplicate of https://github.com/apple/swift-distributed-tracing/issues/80

**Closed by ktoso** 2023-02-24 10:44 UTC
Labels: 1 - triaged
